defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

data:
  bucket: 'deep-learning-projects'
  data_dir: 'data'
  rag_dir: 'data/rag'
  process_raw_data: False
  create_text_data: False
  generate_data: True
  split_data: False
  start_year: 2018
  test_year: 2023

model:
  model_name: 'bigscience/bloomz-560m'   # mistralai/Mistral-7B-Instruct-v0.2, mistralai/Mistral-7B-v0.1,
  load_in_4bit: True
  quant_type: 'nf4'
  quant_compute_dtype: 'float16'
  use_double_quant: False
  cache_dir: '.cache\huggingface'
  hf_token_filepath: 'data/keys/huggingface_token.txt'
  max_length: 512

train:
  num_epochs: 5
  batch_size: 16
  gradient_accumulation_steps: 1
  optim: 'paged_adamw_32bit'
  save_steps: 1000
  logging_steps: 1000
  learning_rate: 2e-4
  weight_decay: 0.001
  out_dir: 'results'

peft:
  method: 'lora'
  r: 64
  lora_a: 16
  target_modules: ['query_key_value']
  dropout: 0.1

evaluate:
  models_dir: 'results/ft_models/bigscience'
  out_dir: 'evaluations'